import { Inter } from "next/font/google";
import "../globals.css";
import { i18nConfig } from '@/i18nConfig'

const inter = Inter({ subsets: ["latin"] });

export async function generateStaticParams() {
  // Get all locales
  const locales = i18nConfig.locales
  // Generate static paths for all locales
  return locales.map(locale => {
    return {
      locale: locale,
    }
  })
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, modal }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        {modal}    
      </body>
    </html>
  );
}
